### PR TITLE
Fix #381 Refunded items still appear on the Invoice, Delivery Notes, …

### LINKED ISSUE #381: Refunded items still appear on the Invoice, Delivery Notes, Invoice.
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When any of the items are refunded, that refunded item still appears on the invoice, delivery note, and receipt.

### Steps to reproduce

1. I have purchased 3 items on the site in a single order.
2 Then, I visited the WC Order and clicked on the Edit Order page.
3. I have refunded one item "Basket" from that order and updated the order.
4. Then I clicked on the "Print Invoice", "Print Delivery Notes", or "Print Receipt" buttons, and the refunded item i.e. Basket is still appearing on the invoice, delivery notes, and receipt.

### Expected behavior

The refunded items should not appear on our invoice, delivery notes, or receipt.

### WordPress Environment

-

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only our plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### Additional field

https://support.tychesoftwares.com/conversation/3631?folder_id=15

### PR DESCRIPTION
**Pull request by gaminikhil**
Fix #381 Refunded items still appear on the Invoice, Delivery Notes, Invoice.

### CODE REVIEW

File: templates/print-order/simple/receipt/print-content.php [hunk 1]
```diff
@@ -205,6 +205,13 @@
 					if ( ! $product ) {
 						continue;
 					}
+					$original_qty = $item->get_quantity();
+					$qty_refunded = $order->get_qty_refunded_for_item( $item_id );
+					$adjusted_qty = $original_qty + $qty_refunded;
+					if ( $adjusted_qty <= 0 ) {
+						continue;
+					}
+					$item['qty'] = $adjusted_qty;
```
Comment (rashmimalpande) [inline templates/print-order/simple/receipt/print-content.php:214]: Same code is used in all templates. Can we create a common function to get the adjusted qty and use in all places?

**Review by rashmimalpande — CHANGES_REQUESTED** [review]
