### PR TITLE
PIF fields were not coming in the invoice.

### LINKED ISSUE #156: Plugin does not work with Product Input Fields for WooCommerce plugin.
**Describe the bug**
The issue is that the print invoice does not show the input fields which we have set with our plugin.

**To Reproduce**
Activate Product Input Fields plugin and Print Invoice and Delivery Notes plugin.
Setup the input field for one product.
Place an order of that product.
Click on the Print Invoice button on the Orders page.
You will not find the input field value on the print invoice.

**Expected behavior**
The input field value should appear on the print invoice/delivery notes/receipt.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/22085

### PR DESCRIPTION
**Pull request by Shasvat7**
PIF fields were not coming in the invoice. This is fixed now.
Fixes #156

### CODE REVIEW

File: woocommerce-delivery-notes/templates/print-order/print-content.php [hunk 1]
```diff
@@ -193,7 +193,39 @@
...
+												foreach( $pif_local_fields as $pif_local_field ) {
+													$key   = $pif_local_field['title'];
+													$value = $pif_local_field['_value'];
+													?>
+													<dt><?php echo wp_kses_post( $key . ' : ' . $value ); ?> </dt>
+													<?php
+												}
+											}
+										}
+
```
Comment (ashokrane) [inline woocommerce-delivery-notes/templates/print-order/print-content.php:227]: Could we move all the above code to another file, like integrations.php ? That way, even in future when we want to add other plugin fields, we can add it in that file.

**Review by ashokrane — APPROVED** [review]
