### PR TITLE
Fix #436 added filter to change the labels for default template.

### LINKED ISSUE #436: Few strings are not showing in the translated language on the invoice.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The strings "Total" and "Subtotal" are not showing in the translated language  “German (Switzerland, Informal)" on the invoice/delivery notes/receipt. 

### Steps to reproduce

I tried to translate the "Total" and "Subtotal" strings of our plugin in the “German (Switzerland, Informal)" language with the Loco Translate plugin.
I can replicate the issue that the translated text is not showing for both these strings on the invoice/delivery notes/receipt. 
Image

I also noticed that the translated text of the "total" string is displaying correctly in the column on the Product details table. The issue appears only in the row of the Product details table.

**NOTE:**
This issue occurs only with the  “German (Switzerland, Informal)" language as I have tried with other two languages of German and it worked fine with it.

### Expected behavior

The strings "total" and "subtotal" should be shown as translated on the invoice into the “German (Switzerland, Informal)" language.

### WordPress Environment

-

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only our plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### Additional field

https://support.tychesoftwares.com/conversation/8905?folder_id=15

### PR DESCRIPTION
**Pull request by gaminikhil**
Fix #436 added filter to change the labels for default template.

```
function custom_translate_order_total_labels( $label, $order ) {
    // Define custom labels without translation
    $custom_labels = array(
        'Subtotal' => 'Product Subtotal',    // Subtotal
        'Shipping' => 'Shipping Charges',    // Shipping
        'Total'    => 'Final Amount',        // Total
    );

    // Return the custom label if it exists, otherwise return the default label
    return isset( $custom_labels[ $label ] ) ? $custom_labels[ $label ] : $label;
}
add_filter( 'wcdn_invoice_order_total_label', 'custom_translate_order_total_labels', 10, 3 );
```

### CODE REVIEW

File: includes/admin/views/Preview_template/default-preview-template.php [hunk 1]
```diff
@@ -308,9 +308,10 @@
 				if ( $totals_arr ) :
 
 					foreach ( $totals_arr as $total ) :
+						$modified_label = apply_filters( 'custom_order_total_label', $total['label'], $key, $order );
```
Comment (rashmimalpande) [inline includes/admin/views/Preview_template/default-preview-template.php:311]: @gaminikhil Add the plugin prefix to the filter name and change it to something like wcdn_invoice_order_total_label.
